name: api gateway
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  production:
    runs-on: ubuntu-latest
    permissions: write-all
    environment: production
    env:
      GCLOUD_DEPLOYMENT_SERVICE_ACCOUNT: ${{ secrets.GCLOUD_DEPLOYMENT_SERVICE_ACCOUNT }}
      GCLOUD_RUNNER_SERVICE_ACCOUNT: ${{ secrets.GCLOUD_RUNNER_SERVICE_ACCOUNT }}
      GCLOUD_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCLOUD_WORKLOAD_IDENTITY_PROVIDER }}
      SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
      DESCRIPTION: ${{ secrets.DESCRIPTION }}
      GATEWAY_TARGET_HEALTH_SERVICE: ${{ secrets.GATEWAY_TARGET_HEALTH_SERVICE }}
      GATEWAY_TARGET_USERS_SERVICE: ${{ secrets.GATEWAY_TARGET_USERS_SERVICE }}
      GATEWAY_PORT: ${{ secrets.GATEWAY_PORT }}
      DOCS: ${{ secrets.DOCS }}
      DOCS_DIR: docs
      GATEWAY_API_KEY_HEADER_NAME: ${{ secrets.GATEWAY_API_KEY_HEADER_NAME }}
      GATEWAY_TARGET_HEALTH_SERVICE_API_KEY: ${{ secrets.GATEWAY_TARGET_HEALTH_SERVICE_API_KEY }}
      GATEWAY_TARGET_USERS_SERVICE_API_KEY: ${{ secrets.GATEWAY_TARGET_USERS_SERVICE_API_KEY }}
      GATEWAY_TARGET_AUTHENTICATION_SERVICE: ${{ secrets.GATEWAY_TARGET_AUTHENTICATION_SERVICE }}
      GATEWAY_TARGET_AUTHENTICATION_SERVICE_API_KEY: ${{ secrets.GATEWAY_TARGET_AUTHENTICATION_SERVICE_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: update Dockerfile
        run: |
          echo "ENV GATEWAY_TARGET_HEALTH_SERVICE=${{ env.GATEWAY_TARGET_HEALTH_SERVICE }}" >> Dockerfile
          echo "ENV GATEWAY_TARGET_USERS_SERVICE=${{ env.GATEWAY_TARGET_USERS_SERVICE }}" >> Dockerfile
          echo "ENV GATEWAY_PORT=${{ env.GATEWAY_PORT }}" >> Dockerfile
          echo "ENV GATEWAY_API_KEY_HEADER_NAME=${{ env.GATEWAY_API_KEY_HEADER_NAME }}" >> Dockerfile
          echo "ENV GATEWAY_TARGET_HEALTH_SERVICE_API_KEY=${{ env.GATEWAY_TARGET_HEALTH_SERVICE_API_KEY }}" >> Dockerfile
          echo "ENV GATEWAY_TARGET_USERS_SERVICE_API_KEY=${{ env.GATEWAY_TARGET_USERS_SERVICE_API_KEY }}" >> Dockerfile
          echo "ENV GATEWAY_TARGET_AUTHENTICATION_SERVICE=${{ env.GATEWAY_TARGET_AUTHENTICATION_SERVICE }}" >> Dockerfile
          echo "ENV GATEWAY_TARGET_AUTHENTICATION_SERVICE_API_KEY=${{ env.GATEWAY_TARGET_AUTHENTICATION_SERVICE_API_KEY }}" >> Dockerfile
          echo "EXPOSE ${{ env.GATEWAY_PORT }}" >> Dockerfile
          echo "CMD [\"node\", \"index.js\"]" >> Dockerfile
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'id_token'
          workload_identity_provider: '${{ env.GCLOUD_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ env.GCLOUD_DEPLOYMENT_SERVICE_ACCOUNT }}'
          id_token_audience: '${{ env.GCLOUD_WORKLOAD_IDENTITY_PROVIDER }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      - name: 'Use gcloud CLI'
        run: 'gcloud run deploy "${{ env.SERVICE_NAME }}" --source . --allow-unauthenticated --description="${{ env.DESCRIPTION }}" --region=us-central1 --port=${{ env.GATEWAY_PORT }} --service-account=${{ secrets.GCLOUD_RUNNER_SERVICE_ACCOUNT }}'
